name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]

body:
  - type: dropdown
    id: version
    attributes:
      label: macOS Version
      description: What version of macOS are you running?
      options:
        - "Sequoia (macOS 15)"
        - "Sonoma (macOS 14)"
        - "Ventura (macOS 13"
        - "Monterey (macOS 12)"
        - "Big Sur (macOS 11)"
        - "Catalina (macOS 10.15)"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: cpu
    attributes:
      label: Apple Silicon or Intel
      options:
        - "Apple Silicon"
        - "Intel"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: wrapper
    attributes:
      label: Wrapper Version
      options:
        - "Wineskin-3.0.7"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: engine
    attributes:
      label: Engine
      description: What Engine where you using
      options:
        - "WS12WineCX23.7.1"
        - "WS12WhiskyWine2.4.4 (not supported)"
        - "WS12WineGPTK1.1 (not supported)"
        - "WS11WineCX21.2.0 (not supported)"
        - "WS11WineCX32Bit21.2.0 (not supported)"
        - "WS11WineCX20.0.4 (not supported)"
        - "WS11WineCX32Bit20.0.4 (not supported)"
      default: 0
    validations:
      required: true
  - type: textarea
    id: appname
    attributes:
      label: Application/Game Name
    validations:
      required: true
  - type: dropdown
    id: render
    attributes:
      label: Render Used
      description: What render backend was used
      options:
        - "WineD3D"
        - "D3DMetal (64-bit only)"
        - "DXVK"
        - "D9VK"
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of problem
      description: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Provide steps to reproduce the behavior.
      value: |
       1.
       2.
       3.
       ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: LastRunWineLog
      description: Please copy/paste the contents of LastRunWine.log.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
