name: Bug Report
description: Report a bug.
type: "Bug"
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Please provide detailed step-by-step instructions on how to reproduce this issue.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: Please provide a clear a detailed description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Please provide LastRunWine.log
      render: bash
    validations:
      required: true
  - type: dropdown
    id: whisky-version
    attributes:
      label: What version of Kegworks are you using?
      options:
        - "3.0.7"
        - "<3.0.6-1"
    validations:
      required: true
  - type: dropdown
    id: mac-version
    attributes:
      label: What version of macOS are you using?
      options:
        - "Sequoia (macOS 15)"
        - "Sonoma (macOS 14)"
        - "Ventura (macOS 13"
        - "Monterey (macOS 12)"
        - "Big Sur (macOS 11)"
        - "Catalina (macOS 10.15)"
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Issue Language
      description: All issues must be written in clear plain English so that all devs are able to read them.
      options:
        - label: Yes my issue is written in English
          required: true
